Thu Jun  6 06:48:52 CEST 2024 + clean test.c

diff --git a/Makefile_push b/Makefile_push
--- a/Makefile_push
+++ b/Makefile_push
@@ -1,5 +1,5 @@
-NAME = so_long
-NAME_BONUS = so_long_bonus
+NAME = push_swap
+NAME_BONUS = checker
 
 CC = cc
 FLAGS = -Wextra -Wall -Werror -g -fPIE
@@ -7,73 +7,62 @@ FLAGS = -Wextra -Wall -Werror -g -fPIE
 
 all: $(NAME)
 
-a: libft mlx $(NAME)
-	clear
+# ╭──────────────────────────────────────────────────────────────────────╮
+# │                  	 	        TESTING                    	         │
+# ╰──────────────────────────────────────────────────────────────────────╯
+
+ARGS = "1 2 3 9 8 7"
+ARGS2 = 1 6 5 7 9 4 8 33
+
+a: $(NAME)
 	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing $@!~");
-	./so_long map/map_correct.ber
+	./$(NAME) $(ARGS)
 
-b: libft mlx $(NAME)
-	clear
-	valgrind ./so_long map/map_bad_path.ber
+b: $(NAME_BONUS)
+	@echo > outfile
+	@$(call print_cat_random, # $(COLOR_5R_3G_1B), # $(COLOR_5R_2G_3B), # $(COLOR_0R_2G_3B), "~ teshing $@! ~");
+	./$(NAME_BONUS) $(ARGS2)
 
-v: libft mlx $(NAME)
-	clear
-	valgrind --leak-check=full --show-leak-kinds=all ./so_long map/map3.ber
 
-# test all map
-m: libft mlx $(NAME)
+test2:	libft $(OBJ)
+	@$(CC) $(OBJ) ./lib/test.c -I$(HEADER_FOLDER) ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_2G_5B), $(COLOR_5R_1G_1B), $(COLOR_3R_2G_5B), $(call pad_word, 10, "Making"), $(call pad_word, 12, "Science"));
+	@valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --trace-children=yes --track-fds=yes \
+	./lib/a.out $(ARGS)
+
+test3:	libft $(OBJ)
+	@$(CC) $(OBJ) ./lib/test.c -I$(HEADER_FOLDER) ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_2G_5B), $(COLOR_5R_1G_1B), $(COLOR_3R_2G_5B), $(call pad_word, 10, "Making"), $(call pad_word, 12, "Science"));
+	./lib/a.out $(ARGS)
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - VALGRIND -
+v: $(NAME) $(NAME_BONUS)
 	@clear
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with too many players!~");
-	@echo "$(COLOR_5R_1G_0B)"
-	-$(VALGRIND) ./so_long map/map_multiplayer.ber
-# 
-	@clear
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with holes in the wall!~");
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with no collectible!~");
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with player trapped!~");
-	@echo "$(COLOR_5R_1G_0B)"
-	-$(VALGRIND) ./so_long map/map_multiplayer.ber
-# 
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with bad map name!~");
-	@echo "$(COLOR_5R_4G_0B)"
-	-$(VALGRIND)  ./so_long map/map_multiplayer.be
-	-$(VALGRIND)  ./so_long map/mapzzzzz.ber
-# 
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with too much arg!~");
-	@echo "$(COLOR_5R_4G_0B)"
-	-$(VALGRIND)  ./so_long map/map_multiplayer.ber map_correct.ber 
-# 
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with a file renamed!!!~");
-	@echo "$(COLOR_5R_4G_0B)"
-	mv ./img/ball_throw.xpm ./img/ball_throw666.xpm
-	-$(VALGRIND)  ./so_long map/map_correct.ber 
-	mv ./img/ball_throw666.xpm ./img/ball_throw.xpm
-# 
-	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing with empty file~");
-	@echo "$(COLOR_5R_4G_5B)"
-	echo > ./map/map_blank.ber
-	-$(VALGRIND)  ./so_long map/map_blank.ber
+	@valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --trace-children=yes --track-fds=yes \
+	./$(NAME_BONUS) $(ARGS)
 
-
-
-w: libft mlx $(NAME)
-	clear
-	valgrind --leak-check=full --show-leak-kinds=all ./so_long map/map_correct.ber
+# lldb: clean all
+# 	@lldb ./$(NAME) $(ARGS)
 
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	        SOURCES                    	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
-SRC = $(wildcard src/*.c)
-OBJ = $(patsubst src/%.c, src/obj/%.o, $(SRC))
-
 SRC_FOLDER = src
 OBJ_FOLDER = src/obj
 HEADER_FOLDER = include
 
+# $(patsubst pattern,replacement,text)
+# $(addprefix prefix, list)
+SRC = $(wildcard src/*.c)
+OBJ = $(patsubst src/%.c, src/obj/%.o, $(SRC))
+
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	        Libft                      	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
+
+# -s: silent
+# -C: change folder before make
 
 libft:
 	@make -sC lib all;
@@ -88,24 +77,18 @@ libtest:
 	@make -sC lib test_color
 
 # ╭──────────────────────────────────────────────────────────────────────╮
-# │                  	 	       MLX		                   	         │
-# ╰──────────────────────────────────────────────────────────────────────╯
-
-mlx:
-	@make -sC ./mlx_linux/
-
-# ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	       PROJECT                   	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
-$(NAME): mlx libft $(OBJ) main.c
-	@clear
-	@if ! $(CC) $(FLAGS) $(OBJ) main.c -I$(HEADER_FOLDER) lib/libft.a ./mlx_linux/libmlx.a -lX11 -lXext -o $(NAME) -lm; then \
-		$(call print_cat, "", $(RED), $(GOLD), $(RED_L), $(call pad_word, 10, "ERROR"), $(call pad_word, 12, "COMPILING..")); \
+$(NAME): libft main.c $(OBJ)
+	@if ! $(CC) $(FLAGS) $(OBJ) main.c -I$(HEADER_FOLDER) lib/libft.a -o $(NAME); then \
+		$(call print_cat, "", $(GOLD), $(RED), $(RED), $(call pad_word, 10, "Problem⠀while"), $(call pad_word, 12, "Compiling..")); \
 		exit 1; \
 	fi
-	$(call print_cat, $(CLEAR), $(GOLD), $(GREEN1), $(GREEN1), $(call pad_word, 10, $(NAME)), $(call pad_word, 12, "Compiled~"));
-
+	@if [ ! -e in ]; then\
+		echo > in;\
+	fi
+	$(call print_cat, $(CLEAR), $(GOLD), $(GREEN1), $(GOLD), $(call pad_word, 10, $(NAME)), $(call pad_word, 12, "Compiled~")); \
 
 src/obj/%.o: src/%.c
 	@if [ ! -e $(OBJ_FOLDER) ]; then\
@@ -120,73 +103,47 @@ src/obj/%.o: src/%.c
 # │                  	 	       BONUS	                   	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
-SRC_B = $(wildcard src_bonus/*.c)
-OBJ_B = $(patsubst src_bonus/%.c, src_bonus/obj/%.o, $(SRC_B))
-
-OBJ_FOLDER_B = src_bonus/obj
-
-bonus: mlx libft $(OBJ_B) main_bonus.c
-	@clear
-	@if ! $(CC) $(FLAGS) $(OBJ_B) main_bonus.c -I$(HEADER_FOLDER) lib/libft.a ./mlx_linux/libmlx.a -lX11 -lXext -o $(NAME_BONUS) -lm; then \
-		$(call print_cat, "", $(RED), $(GOLD), $(RED_L), $(call pad_word, 10, "ERROR"), $(call pad_word, 12, "COMPILING..")); \
+$(NAME_BONUS): libft main_bonus.c $(OBJ)
+	@if ! $(CC) $(FLAGS) $(OBJ) main_bonus.c -I$(HEADER_FOLDER) lib/libft.a -o $(NAME_BONUS); then \
+		$(call print_cat, "", $(GOLD), $(RED), $(RED), $(call pad_word, 10, "Problem⠀while"), $(call pad_word, 12, "Compiling..")); \
 		exit 1; \
 	fi
-	$(call print_cat, $(CLEAR), $(GOLD), $(GREEN1), $(COLOR_4R_1G_5B), $(call pad_word, 10, $(NAME_BONUS)), $(call pad_word, 12, "Compiled~"));
+	@$(call print_cat, $(CLEAR), $(COLOR_5R_1G_5B), $(COLOR_1R_2G_4B), $(COLOR_5R_1G_0B), $(call pad_word, 10, $(NAME_BONUS)), $(call pad_word, 14, "All⠀ready~"));
 
-
-src_bonus/obj/%.o: src_bonus/%.c
-	@if [ ! -e $(OBJ_FOLDER_B) ]; then\
-		mkdir -p $(OBJ_FOLDER_B);\
-	fi
-	@if ! $(CC) -c $(FLAGS) -I$(HEADER_FOLDER) $< -o $@; then \
-		$(call print_cat_error, $(RED), $(RED_L)); \
-		exit 1; \
-	fi
+bonus: $(NAME_BONUS)
 
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	       OTHERS	                   	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
 test:	libft
-	@cc ./lib/test.c ./lib/libft.a -o ./lib/a.out
-	$(call print_cat, $(CLEAR), $(COLOR_1R_0G_5B), $(COLOR_5R_1G_0B), $(COLOR_0R_2G_5B), $(call pad_word, 10, "Making"), $(call pad_word, 12, "Science"));
-	@lib/a.out
+	@$(CC) ./lib/test.c ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_0G_5B), $(COLOR_5R_1G_0B), $(COLOR_0R_2G_5B), $(call pad_word, 10, "Making"), $(call pad_word, 12, "Science"));
+	@lib/a.out $(ARGS2)
 
 vtest:	libft
-	@cc -g3 ./lib/test.c ./lib/libft.a -o ./lib/a.out
-	$(call print_cat, $(CLEAR), $(RED), $(GOLD), $(BLUE1), $(call pad_word, 10, "TESTING"), $(call pad_word, 12, "SCIENCE"));
-	@echo "$(COLOR_5R_1G_0B)"
-	@valgrind lib/a.out
+	@$(CC) -g3 ./lib/test.c ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(RED), $(GOLD), $(BLUE1), $(call pad_word, 10, "TESTING"), $(call pad_word, 12, "SCIENCE"));
+	@valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --trace-children=yes --track-fds=yes \
+	./lib/a.out $(ARGS)
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - CLEANUP -
 clean:
-	@rm -rf $(OBJ_FOLDER)
-	$(call print_cat, $(CLEAR), $(COLOR_2R_2G_5B), $(COLOR_3R_2G_0B), $(COLOR_4R_5G_0B), $(call pad_word, 10, "Objects"), $(call pad_word, 12, "Exterminated"));
+	@rm -rf $(OBJ_FOLDER) outfile
+	@$(call print_cat, $(CLEAR), $(COLOR_2R_2G_5B), $(COLOR_3R_2G_0B), $(COLOR_4R_5G_0B), $(call pad_word, 10, "Objects"), $(call pad_word, 12, "Exterminated"));
 
 fclean: clean
-	@rm -rf $(NAME) $(NAME_BONUS)
-	@make -sC lib clean_silent;
-	$(call print_cat, $(CLEAR), $(COLOR_1R_2G_0B), $(COLOR_3R_0G_0B), $(COLOR_2R_1G_0B), $(call pad_word, 10, "All⠀clean"), $(call pad_word, 12, "Miaster"));
+	@rm -f $(NAME) $(NAME_BONUS) in
+	@make -sC lib clean_silent
+	@rm -rf traces
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_2G_0B), $(COLOR_3R_0G_0B), $(COLOR_2R_1G_0B), $(call pad_word, 10, "All⠀clean"), $(call pad_word, 12, "Miaster"));
 
-re: fclean all
+re: fclean all bonus
 
-re_bonus: fclean
-
+# .PHONY target is typically used to declare targets that are not actual files but rather are just actions to be performed by make, like clean or all.
 .PHONY: all clean fclean re bonus
 
 .SILENT: $(NAME) bonus
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - VALGRIND -
-VALGRIND = valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --track-fds=yes
-# VALGRIND = valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --trace-children=yes --track-fds=yes
-#
-# ARGS = infile "ls -la" "wc -l" outfile
-#
-# valgrind: clean all
-# 	@valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s \
-# 	--track-origins=yes --trace-children=yes --track-fds=yes --track-origins=yes \
-# 	./$(NAME) $(ARGS)
-# lldb: clean all
-# 	@lldb ./$(NAME) $(ARGS)
 
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	       PRINT                     	         │
@@ -233,15 +190,7 @@ define print_cat
 	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠉⠐⠒⠠⠤⠤⠤⠤⠔⠂⠠⠤⠤⠤⠄⠐⠒⠂⠉⠉⠉⠉⠉⠁\n$(RESET)"
 endef
 
-# $(call print_cat_test, $(COLOR_5R_3G_1B), $(COLOR_0R_2G_3B), $@, "~ teshing $@! ~");
-define print_cat_test
-	echo "$(2)\
-	\t$(3)$(1)\t⠀╱|、\n\
-	\t\t(˚ˎ。7⠀⠀⠀$(2)$(4)$(1)\n\
-	\t\t⠀|、˜\\\\\n\
-	\t\t⠀じしˍ)ノ\n$(RESET)"
-endef
-
+# $(call print_cat_error, $(RED), $(RED_L));
 define print_cat_error
 	echo "$(2)\
 	\tにゃ~$(1)\t⠀╱|、\n\
@@ -250,6 +199,41 @@ define print_cat_error
 	\t\t⠀じしˍ)ノ\n$(RESET)"
 endef
 
+# $(call print_cat_test, $(COLOR_5R_3G_1B), $(COLOR_0R_2G_3B), $@, "~ teshing $@! ~");
+define print_cat_test
+	echo "$(CLEAR) $(2)\
+	\t$(3)$(1)\t⠀╱|、\n\
+	\t\t(˚ˎ。7⠀⠀⠀$(2)$(4)$(1)\n\
+	\t\t⠀|、˜\\\\\n\
+	\t\t⠀じしˍ)ノ\n$(RESET)"
+endef
+
+# $(call print_cat_random, # $(random_color), # $(random_color), # $(random_color), "~ teshing $@! ~");
+define print_cat_random
+	echo "$(CLEAR) $(2)\
+	\tにゃ~$(1)\t⠀╱|、\n\
+	\t\t(˚ˎ。7⠀⠀⠀$(3)$(4)$(1)\n\
+	\t\t⠀|、˜\\\\\n\
+	\t\t⠀じしˍ)ノ\n$(RESET)"
+endef
+
+# //////////////////////////////////////
+# @echo "Random color escape sequence: $(call random_color_escape)"
+# Define a function to generate a random color code
+define random_colora
+	\033[38;5;$(shell echo $$((RANDOM % 256)))m
+endef
+
+random_number := $(shell od -An -N1 -tu1 /dev/urandom)
+
+define random_number_func
+	$(random_number)
+endef
+
+random_number:
+	@echo $(random_number)
+
+# //////////////////////////////////////
 # 					Define all 256 colors
 BLACK = \033[38;5;0m
 RED = \033[38;5;1m
